console.log('L4DWiki_PageName:',wgPageName)
function loggedIn(username){return(typeof username==='string')}const hasClass=(function(){var reCache={};return function(element,className){return(reCache[className]?reCache[className]:(reCache[className]=new RegExp("(?:\\s|^)"+className+"(?:\\s|$)"))).test(element.className)}})()
var autoCollapse=1;var collapseCaption="hide";var expandCaption="show";function collapseTable(tableIndex){var Button=document.getElementById("collapseButton"+tableIndex);var Table=document.getElementById("collapsibleTable"+tableIndex);if(!Table||!Button){return false;}var Rows=Table.rows;if(Button.firstChild.data==collapseCaption){for(var i=1;i<Rows.length;i++){Rows[i].style.display="none";}Button.firstChild.data=expandCaption;}else{for(var i=1;i<Rows.length;i++){Rows[i].style.display=Rows[0].style.display;}Button.firstChild.data=collapseCaption;}}function createCollapseButtons(){var tableIndex=0;var collapseIndex=0;var NavigationBoxes=new Object();var Tables=document.getElementsByTagName("table");for(var i=0;i<Tables.length;i++){if(hasClass(Tables[i],"collapsible")){var HeaderRow=Tables[i].getElementsByTagName("tr")[0];if(!HeaderRow)continue;var Header=HeaderRow.getElementsByTagName("th")[0];if(!Header)continue;NavigationBoxes[tableIndex]=Tables[i];Tables[i].setAttribute("id",
"collapsibleTable"+tableIndex);var Button=document.createElement("span");var ButtonLink=document.createElement("a");var ButtonText=document.createTextNode(collapseCaption);Button.style.styleFloat="right";Button.style.cssFloat="right";Button.style.fontWeight="normal";Button.style.textAlign="right";Button.style.width="6em";Button.className="t_show_hide";ButtonLink.style.color=Header.style.color;ButtonLink.setAttribute("id","collapseButton"+tableIndex);ButtonLink.setAttribute("href","javascript:collapseTable("+tableIndex+");");ButtonLink.appendChild(ButtonText);Button.appendChild(document.createTextNode("["));Button.appendChild(ButtonLink);Button.appendChild(document.createTextNode("]"));Header.insertBefore(Button,Header.childNodes[0]);if(!hasClass(Tables[i],"nocount")){collapseIndex++;}tableIndex++;}}for(var i=0;i<tableIndex;i++){if(hasClass(NavigationBoxes[i],"collapsed")||(collapseIndex>=autoCollapse&&hasClass(NavigationBoxes[i],"autocollapse"))){collapseTable(i);}else if(hasClass(
NavigationBoxes[i],"innercollapse")){var element=NavigationBoxes[i];while(element=element.parentNode){if(hasClass(element,"outercollapse")){collapseTable(i);break;}}}}}addOnloadHook(createCollapseButtons);importArticles({type:"script",articles:["w:c:dev:MediaWiki:Countdown/code.js"]});ajaxPages="Special:RecentChanges,Special:Watchlist,";function setCookie(c_name,value,expiredays){var exdate=new Date()
exdate.setDate(exdate.getDate()+expiredays)
document.cookie=c_name+"="+escape(value)+((expiredays==null)?"":";expires="+exdate.toGMTString())}function getCookie(c_name){if(document.cookie.length>0){c_start=document.cookie.indexOf(c_name+"=")
if(c_start!=-1){c_start=c_start+c_name.length+1
c_end=document.cookie.indexOf(";",c_start)
if(c_end==-1)c_end=document.cookie.length
return unescape(document.cookie.substring(c_start,c_end))}}return""}function getXmlHttpRequestObject(){if(window.XMLHttpRequest){return new XMLHttpRequest();}else if(window.ActiveXObject){return new ActiveXObject("Microsoft.XMLHTTP");}else{}}getRCDataRO=getXmlHttpRequestObject();var cr=new RegExp("\r","gm");var lf=new RegExp("\n","gm");var endText=new RegExp('</div>[\t\s]*?<!-- end content -->[\t\s]*?<div class="visualClear">',"mi");var rcTimer;var rcRefresh=60000;function preloadAJAXRC(){if(skin=="monaco"){s=1;}else{s=0;}ajaxRCCookie=(getCookie("ajaxload-"+wgPageName)=="on")?true:!1;document.getElementsByTagName("h1")[0].innerHTML+=' <span style="font-size: xx-small; border-bottom: 1px dotted; cursor:help;" title="Enable auto-refreshing page loads">AJAX:</span><input type="checkbox" id="ajaxRCtoggle" onClick="toggleRC();">';document.getElementById("ajaxRCtoggle").checked=ajaxRCCookie;if(getCookie("ajaxload-"+wgPageName)=="on")loadRCData();}function toggleRC(){if(document.
getElementById("ajaxRCtoggle").checked==true){setCookie("ajaxload-"+wgPageName,"on",30);loadRCData();}else{setCookie("ajaxload-"+wgPageName,"off",30);clearTimeout(rcTimer);}}function loadRCData(){if(getRCDataRO.readyState==4||getRCDataRO.readyState==0){if(location.href.indexOf("/wiki/")){rcURL="http://"+location.hostname+"/wiki/"+wgPageName+location.search;}else{rcURL="http://"+location.hostname+"/"+wgPageName+location.search;}getRCDataRO.open("GET",rcURL,true);getRCDataRO.onreadystatechange=parseRCdata;getRCDataRO.send(null);}}function parseRCdata(){if(getRCDataRO.readyState==4){textFilter=new RegExp('<div id="bodyContent">.*?</div>[\t\s]*?<!-- end content -->[\t\s]*?<div class="visualClear">',"i");rawRCdata=getRCDataRO.responseText.replace(cr,"").replace(lf,"");filteredRCdata=textFilter.exec(rawRCdata);updatedText=filteredRCdata[0].replace('<div id="bodyContent">',"").replace(endText,"");document.getElementById("bodyContent").innerHTML=updatedText+document.getElementById(
"bodyContent").innerHTML;rcTimer=setTimeout("loadRCData();",rcRefresh);}}if(ajaxPages.indexOf(wgPageName)!=-1){addOnloadHook(preloadAJAXRC);}function fetchUsernameElements(){const Elements=document.getElementsByTagName("span")
const array=[]
for(var i=0;i<Elements.length;i++){if(hasClass(Elements[i],"current-user-name")){array.push([Elements[i],"name","User"])}else if(hasClass(Elements[i],"current-user-gender")){array.push([Elements[i],"gender","Unknown gender"])}else if(hasClass(Elements[i],"current-user-date")){array.push([Elements[i],"registration","Anon"])}}return array}function renderUserInfo(elements){return function(data){const user=data.query.users[0]
elements.forEach(function(element){element[0].innerHTML=user[element[1]]||element[2]})}}function fetchUser(){const elements=fetchUsernameElements()
if(!elements.length)return
const username=mw.config.get('wgUserName')
if(loggedIn(username)){return $.ajax({crossDomain:!0,url:'https://community.wikia.com/api.php',type:'POST',data:{action:'query',list:'users',ususers:username,usprop:'registration|gender',format:'json'},dataType:'JSONP',success:renderUserInfo(elements),error:function(error){console.error('Error fetching userInfo:',error)}})}}addOnloadHook(fetchUser);;;mw.loader.state({"site":"ready"});

/* cache key: left4dead:resourceloader:filter:minify-js:7:7524c4be2e20c53f89a2f3246f919ae1 */